version: "3.9"
services:
  newsapp:
    build: .
    ports:
      - "19000:19000" # Metro bundler
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
